# Use docker-based build environment (instead of openvz)
sudo: false

language: java

addons:
  apt:
    packages:
      - oracle-java8-installer

jdk: oraclejdk8

cache:
directories:
- '$HOME/.m2/repository'
install: /bin/true
